on: 
  - push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: printa hello world
        run: echo "Hello world"
      - name: verifica versao do node e npm
        run: |
          node -v
          npm -v